### ISSUE TITLE
s3p summarize byte output dosent match total size

### ISSUE THREAD

**Issue by patrickhisshion-okta** [generalui/s3p#64]
```
REDACTED, totalSize: 15.63tB REDACTED  DONE

size:           17187655569827

maxSizeKey:
  REDACTED

  bytes:
    size:  2320238909

  kilobytes:
    size:  301245682284
   
  gigabytes:
    size:  5087848004736

human: size: 15.63tB, REDACTED
```

I'm not sure how to read the "size" in each of the unit sections.

2320238909 bytes is 0.002320238909 TB
301245682284 kb is 0.301245682284 TB
etc.

size above the maxSizeKey is 17187655569827, I wasn't sure what unit this was so I assumed bytes which is 17.187655569827001 TB

Total size calculated is 15.63TB

How do we read this?
